
# List of Figures
\listoffigures

{{< pagebreak >}}

# List of Tables
\listoftables

{{< pagebreak >}}

# Executive Summary {.unnumbered}

'Ōpakapaka ({{< var species.scientific >}}) is one of Hawai'i's most culturally significant species and is a member of the Deep 7 bottomfish complex, a group of six deep water snapper and one grouper. The Deep 7 complex is currently assessed with a single surplus production model however, since {{< var species.common >}} comprises over 50% of the commercial catch of Deep 7 and is one of the few species with enough data for an age-structured, integrated model, a single-species model has been developed for research. One key source of information for the Deep 7 complex assessment model as well as for the  {{< var species.common >}} single-species model is the Bottomfish Fishery-Independent Survey in Hawai'i (BFISH) which provides index of abundance and length composition data. The BFISH is an annual survey conducted around the main Hawaiian islands since 2016 that specifically targets deep-water snapper and grouper. The sampling design historically integrated two gear types, a remote stereo-video camera system and a hook-and-line research fishing. However, in response to operational and financial constraints, the camera gear was removed from the survey and it now relies solely on research fishing. The number of grids the BFISH surveys in a given year has fluctuated depending on funding and logistical constraints. Because the number of sampled grids directly impacts the uncertainty of the abundance indices, it is important to evaluate alternative sampling strategies to understand the relationship between number of grids sampled and the impact on key model outputs used in management of the fishery. We wanted to evaluate whether we could optimize the fishery-independent survey for {{< var species.common >}} by first looking at the effect of varying levels of survey effort on the model's ability to estimate key stock quantities under periods of normal or poor recruitment and second, evaluate the impact of alternative gear type (and the resulting selectivity) on the assessment model performance, particularly under poor recruitment conditions. 

We simulated 100 operating model/estimation model pairs for 14 scenarios to test the impact of different survey efforts and gear configurations on the {{< var species.common >}} single-species model. For the poor recruitment condition, we simulated a 40% sustained decline in mean recruitment for 25 years. We tested five effort scenarios: high (HSE), intermediate (ISE), low (LSE), extra low (XLSE), and none (NSE) (fishery-dependent data only) under both normal and poor recruitment conditions. We also tested a change in selectivity (from dome-shaped to logistic) for HSE, ISE, and LSE efforts under poor recruitment conditions. To compare bias and precision of each scenario, we calculated median relative error for spawning stock biomass, fishing mortality, age-0 recruitment, and reference points (SSB/SSB~MSST~ and F/F~MSY~).  

We found that under normal recruitment conditions, all sampling scenarios performed similarly well, with precision decreasing slightly as effort decreased. Under poor recruitment conditions, we found that bias increased and precision decreased as sampling effort decreased. Additionally, the scenario with no survey effort (NSE) highlighted the dangers of relying only on fishery-dependent data. Key management reference points were estimated fairly well by the model at all survey efforts but precision degraded as effort decreased. We found that under poor recruitment, the majority of models were unable to recover the true reference point values and that terminal year SSB/SSB~MSST~ was overestimated over 50% of the time for all effort scenarios.  

We also found that changing the research fishing gear configuration from dome-shaped to logistic had an interesting effect on model performance. Looking at terminal year SSB specifically, for HSE and LSE, the relative error for SSB was comparable or marginally better than the dome-shaped selectivity model, however, for ISE, it was noticeably higher for logistic selectivity than dome-shaped. We believe this is because of confounding parameters and identifiability issues that are emphasized at that level of survey effort. An informative prior on catchability under ISE effort improved the terminal year SSB bias from 13.4% to 7.6%.  

The results of this simulation highlight the importance of maintaining adequate survey effort; we suggest maintaining effort levels high enough to keep the index CV between 15-18% for more reliable stock assessment estimates. And particularly in times of poor recruitment, increased monintoring should be considered. Additionally, any changes to gear configuration may result in unexpected modelling difficulties and adequate research should be done to understand how new gear configurations impact catchability. 




